python trial_3_train.py 
/home/cs4li/tensorflow/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
train data shape: (50000, 32, 32, 3)
50000 train samples
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_1 (Conv2D)            (None, 32, 32, 96)        2688      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 96)        83040     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 32, 96)        83040     
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 16, 16, 192)       166080    
_________________________________________________________________
dropout_1 (Dropout)          (None, 16, 16, 192)       0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 16, 16, 192)       331968    
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 16, 16, 192)       331968    
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 8, 8, 192)         331968    
_________________________________________________________________
dropout_2 (Dropout)          (None, 8, 8, 192)         0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 8, 8, 192)         331968    
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 8, 8, 192)         37056     
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 8, 8, 100)         19300     
_________________________________________________________________
global_average_pooling2d_1 ( (None, 100)               0         
_________________________________________________________________
activation_1 (Activation)    (None, 100)               0         
=================================================================
Total params: 1,719,076
Trainable params: 1,719,076
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
2018-02-14 16:40:11.589522: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-02-14 16:40:11.672810: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-14 16:40:11.673258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: Quadro M1200 major: 5 minor: 0 memoryClockRate(GHz): 1.148
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.04GiB
2018-02-14 16:40:11.673292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro M1200, pci bus id: 0000:01:00.0, compute capability: 5.0)
195/195 [==============================] - 133s 682ms/step - loss: 4.5867 - acc: 0.0139
Epoch 2/10
195/195 [==============================] - 126s 646ms/step - loss: 4.4540 - acc: 0.0353
Epoch 3/10
195/195 [==============================] - 126s 647ms/step - loss: 4.1735 - acc: 0.0750
Epoch 4/10
195/195 [==============================] - 128s 656ms/step - loss: 3.9149 - acc: 0.1192
Epoch 5/10
195/195 [==============================] - 125s 640ms/step - loss: 3.6331 - acc: 0.1628
Epoch 6/10
195/195 [==============================] - 124s 638ms/step - loss: 3.3807 - acc: 0.2034
Epoch 7/10
195/195 [==============================] - 129s 659ms/step - loss: 3.1707 - acc: 0.2393
Epoch 8/10
195/195 [==============================] - 127s 653ms/step - loss: 3.0312 - acc: 0.2638
Epoch 9/10
195/195 [==============================] - 127s 651ms/step - loss: 2.9123 - acc: 0.2844
Epoch 10/10
195/195 [==============================] - 124s 638ms/step - loss: 2.7609 - acc: 0.3140
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f2167bd1390>>
Traceback (most recent call last):
  File "/home/cs4li/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 702, in __del__
TypeError: 'NoneType' object is not callable
